### ISSUE TITLE
Make sure info pop up points to park

### ISSUE THREAD

**Issue by mikekokuba** [friendlycode/grparks#37]
When selecting certain parks from the list the info pop up doesn't point to the park but instead it points just outside the park or on the border of the park.

![screen shot 2016-02-06 at 9 30 23 am](https://cloud.githubusercontent.com/assets/6855714/12868114/a46ae7dc-ccb4-11e5-9816-7ae0ecca8bff.png)
![screen shot 2016-02-06 at 9 32 23 am](https://cloud.githubusercontent.com/assets/6855714/12868115/a46b3bce-ccb4-11e5-9385-c4b10c5bfbb6.png)

**Comment by joel6653** [comment]
Some of the parks are very oddly shaped. The computation for where to locate the popup is done with a "bounding box" (that is, a rectangle that encompasses the entire park). The popup points to the center of this rectangle.  It works very well for rectangle-ish parks, but not so well for Riverside or Canal or some others.  I considered trying to locate the popup along the top edge, but even that won't work for some other parks, due to their having grossly uneven top edges (Riverside would be one of these, too).  The best solution is a lot more work (but only one-time): identify, by geographic coordinates the REAL center of each park, so that the popup-placement can use that value instead of computing its own.

**Comment by joel6653** [comment]
If I bring this up at our next meeting, looking for additional input or suggestions, and no one has any more to contribute, I think this issue can be closed.

**Comment by MuellerL** [comment]
While (slightly) annoying, this does not appear to be a critical issue. If there's no easy solution, I wouldn't worry too much for now. It's always something we can fix down the line once we get a "version 1" out there.

**Comment by joel6653** [comment]
Closing. See issue #40 for a continuation of this topic (a proposed resolution).
